[[sources]]
id = "solarflow_supabase"
type = "postgres"
host = "aws-1-us-east-1.pooler.supabase.com"
port = 6543
database = "postgres"
user = "postgres.fqaeyzndqyyfugwmkidh"
password = "U6bu0q7OkGNQccIA"
sslmode = "require"
